name: Node Tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Jest
      uses: cd backend && stefanoeb/jest-action@1.0.2
      with:
        jestArgs: --runInBand ./test
